#!/usr/bin/env ansible-playbook

- name: Configure the new server.
  hosts: PKI
  gather_facts: true
  vars_file:
    - defaults/vault.yml
    - defaults/certificates.yml
  become: true
  roles:
    - ansible-role-certifs
