#!/usr/bin/env ansible-playbook

- name: Configure the new server.
  hosts: PKI
  gather_facts: true
  user: root
  vars_file:
    - defaults/vault.yml
    - defaults/certificates.yml
  roles:
    - certifs
