---
#Tasks for generating the Root Authority certificate

- name: Generate the architecture for certificate storage.
  block:
  - ansible.builtin.file:
      name: "{{ item }}"
      state: "directory"
      owner: "{{ admin_linux }}"
      group: "{{ admin_linux }}"
      mode: 0700
    loop:
      - "{{ path_pki }}"
      - "{{ path_domain }}"
      - "{{ path_conf }}"
      - "{{ path_domain }}/{{ children }}_ca"

  - ansible.builtin.file:
      name: "{{ path_domain }}/{{ children }}_ca/{{ item }}"
      state: directory
      owner: "{{ admin_linux }}"
      group: "{{ admin_linux }}"
      mode: 0700
    loop:
      - public
      - private
      - export
      - request
      - signed
      - crl
      - ".pki"

  - ansible.builtin.copy:
      src: "{{ item }}"
      dest: "{{ path_pki }}/{{ domain }}/{{ children }}_ca/.pki/{{ item }}"
      owner: "{{ admin_linux }}"
      group: "{{ admin_linux }}"
      mode: 0600
    loop:
      - index
      - index.attr
      - serial

- name: "Generate openssl config."
  template:
    src: "openssl.config.j2"
    dest: "{{ path_conf }}/openssl.{{ children }}"
    owner: "{{ admin_linux }}"
    group: "{{ admin_linux }}"
    mode: 0600

#Generate the certificates

- name: Generate the key file.
  community.crypto.openssl_privatekey:
    type: "{{ certificate_children.algo }}"
    curve: "{{ certificate_children.curve | default(omit) }}"
    size: "{{ certificate_children.size | default(omit) }}"
    path: "{{ path_domain }}/{{ children }}_ca/private/{{ certs_name[children] | upper }}.key"
    passphrase: '{{ certificate_children.pass | default(omit) }}'
    cipher: 'auto'
    mode: 0600
    owner: '{{ admin_linux }}'
    group: '{{ admin_linux }}'
  register: private_key

- name: Generate the csr associate.
  community.crypto.openssl_csr:
    common_name: "{{ certificate_children.cn }}"
    country_name: "{{ certificate_children.country | default('{{ default.personalize.country }}') }}"
    state_or_province_name: "{{ certificate_children.state | default('{{ default.personalize.state }}') }}"
    locality_name: "{{ certificate_children.locality | default('{{ default.personalize.locality }}') }}"
    organization_name: "{{ certificate_children.o | default('{{ default.personalize.o }}') }}"
    organizational_unit_name: "{{ certificate_children.ou | default('{{ default.personalize.ou }}') }}"
    email_address: "{{ certificate_children.email | default('{{ default.personalize.email }}') }}"
    basic_constraints: "{{ certificate_children['type']['basic_constraints'] | default(omit) }}"
    basic_constraints_critical: "{{ certificate_children['type']['basic_constraints_critical'] | default(omit) }}"
    key_usage: "{{ certificate_children['type']['KU'] | default(omit) }}"
    key_usage_critical: "{{ certificate_children['type']['ku_critical'] | default(omit) }}"
    extended_key_usage: "{{ certificate_children['type']['EKU'] | default(omit) }}"
    extended_key_usage_critical: "{{ certificate_children['type']['eku_critical'] | default(omit) }}"
    subject_alt_name: "{{ certificate_children.san | default(omit) }}"
    crl_distribution_points: "{{ crl_delegated }}"
    path: "{{ path_domain }}/{{ authority }}_ca/request/{{ certs_name[children] | upper }}.csr"
    privatekey_path: "{{ private_key.filename }}"
    privatekey_passphrase: "{{ certificate_children.pass | default(omit) }}"
    mode: 0600
    owner: '{{ admin_linux }}'
    group: '{{ admin_linux }}'
    return_content: yes
  register: signing_request

- name: Sign certificate.
  community.crypto.x509_certificate:
    csr_content: "{{ signing_request.csr }}"
    path: "{{ path_domain }}/{{ children }}_ca/public/{{ certs_name[children] | upper }}.pem"
    provider: "{{ certificate_children.provider | default('selfsigned') }}"
    privatekey_path: "{{ private_key.filename | default(omit) }}"
    privatekey_passphrase: "{{ certificate_children.pass | default(omit) }}"
    selfsigned_digest: "{{ ca.digest | default(omit) }}"
    selfsigned_not_before: "{{ ca.before | default(omit) }}"
    selfsigned_not_after: "{{ ca.after | default(omit) }}"
    ownca_path: "{{ path_domain }}/{{ authority }}_ca/public/{{ certs_name[authority] | upper }}.pem"
    ownca_privatekey_path: "{{ path_domain }}/{{ authority }}_ca/private/{{ certs_name[authority] | upper }}.key"
    ownca_privatekey_passphrase:  "{{ ca.pass | default(omit) }}"
    ownca_digest: "{{ ca.digest | default(omit) }}"
    ownca_not_before: "{{ ca.before | default(omit) }}"
    ownca_not_after: "{{ ca.after | default(omit) }}"
    mode: 0600
    owner: '{{ admin_linux }}'
    group: '{{ admin_linux }}'
    return_content: yes
  register: certificate

- name: export certificate
  ansible.builtin.copy:
    dest: "{{ path_domain }}/{{ children }}_ca/public/{{certs_name[children] | upper }}.pem"
    content: "{{ certificate.certificate }}"

- name: Get the serial.
  community.crypto.x509_certificate_info:
    content: "{{ certificate.certificate }}"
  register: certificate_info

- name: Generate the serial of the PKI.
  ansible.builtin.copy:
    content: "{{ certificate_info.serial_number +1 }}"
    dest: "{{ path_pki }}/{{ domain }}/{{ children }}_ca/.pki/serial"

