---
#Tasks file for ansible-role-certifs

- name: Include password lookup
  include_tasks:
    file: "password.yml"
  args:
    apply:
      delegate_to: localhost
  tags: always

- ansible.builtin.set_fact:
    ansible_become_password: "{{ ansible_default.password }}"

- name: Include os specific tasks.
  ansible.builtin.include_tasks:
    file: "os/{{ ansible_pkg_mgr }}.yml"
  args:
    apply:
      become: yes
      become_user: "{{ admin.username }}"
  tags: internet

- name: Install cryptography library
  ansible.builtin.pip:
    name: cryptography
    state: latest

- name: Install Own Private Key Infrastructure
  block:
  - name: Install root ca
    include_tasks: "authority.yml"
    vars:
      authority: root
      children: root
      certificate_children: "{{ certificate_root }}"
    args:
      apply:
        delegate_to: localhost
        become: yes
        become_user: "{{ admin.username }}"

  - name: Install delegated ca
    include_tasks: "authority.yml"
    vars:
      authority: root
      children: delegated
      certificate_children: "{{ certificate_delegated }}"
    args:
      apply:
        become: yes
        become_user: "{{ admin.username }}"
  when: install_pki is true
# Comment vérifier que le certificat n'existe pas déjà ?

- name: Generate the certificate
  include_tasks: "clients.yml"
