---
#Tasks file for ansible-role-certifs

- name: Install cryptography library
  ansible.builtin.pip:
    name: cryptography
    state: latest

- name: Include password lookup
  include_tasks:
    file: "password.yml"
  args:
    apply:
      delegate_to: localhost
  tags: always

- name: Install Own Private Key Infrastructure
  block:
  - name: Install root ca
    include_tasks: "authority.yml"
    vars:
      authority: root
      children: root
      certificate_children: "{{ certificate_root }}"

  - name: Install delegated ca
    include_tasks: "authority.yml"
    vars:
      authority: root
      children: delegated
      certificate_children: "{{ certificate_delegated }}"

  when: install_pki is true
# Comment vérifier que le certificat n'existe pas déjà ?

- name: Generate the certificate
  include_tasks: "clients.yml"
