---


#root_ca_login
- name: "Create a new password, or get the existing item for {{ root_ca_login.username }}"
  block:
  - ansible.builtin.stat:
      path: "{{ keepass.database }}"
    register: kdbx

  - keepass:
      database: "{{ keepass.database }}"
      password: "{{ keepass.passwd | default(omit) }}"
      keyfile: "{{ keepass.keyfile | default(omit) }}"
      password_length: "{{ keepass.length }}"
      purpose: "{{root_ca_login.username }}@{{ domain }}"
      username: "{{ root_ca_login.username }}"
    when: kdbx.stat.mimetype is defined and kdbx.stat.mimetype == 'application/octet-stream'
    register: root_ca_login_tempo

  - ansible.builtin.set_fact:
      root_ca_login:
        username: "{{ root_ca_login.username }}"
        password: "{{ root_ca_login_tempo.password | default('') }}"
      when: root_ca_login_tempo.skipped is not defined

  delegate_to: localhost
  when: root_ca_login.password == ''
  ignore_errors: true

- name: "Generate the password if is empty."
  ansible.builtin.set_fact:
    root_ca_login:
      username: "{{ root_ca_login.username }}"
      password: "{{ lookup('password', '{{ credential_store }}/{{ root_ca_login.username }}@{{ domain }}_secret chars=ascii_letters,digits length=32') }}"
  when:  root_ca_login.password == ''


#delegated_ca_login
- name: "Create a new password, or get the existing item for {{ delegated_ca_login.username }}"
  block:
  - ansible.builtin.stat:
      path: "{{ keepass.database }}"
    register: kdbx

  - keepass:
      database: "{{ keepass.database }}"
      password: "{{ keepass.passwd | default(omit) }}"
      keyfile: "{{ keepass.keyfile | default(omit) }}"
      password_length: "{{ keepass.length }}"
      purpose: "SQL - {{delegated_ca_login.username }}@{{ server.name }}"
      username: "{{ delegated_ca_login.username }}"
    when: kdbx.stat.mimetype is defined and kdbx.stat.mimetype == 'application/octet-stream'
    register: delegated_ca_login_tempo

  - ansible.builtin.set_fact:
      delegated_ca_login:
        password: "{{ delegated_ca_login_tempo.password  | default('') }}"
      when: delegated_ca_login_tempo.skipped is not defined

  delegate_to: delegated_ca_loginhost
  when: delegated_ca_login.password == ''
  ignore_errors: true

- name: "Generate the password if is empty."
  ansible.builtin.set_fact:
    delegated_ca_login:
      username: "{{ delegated_ca_login.username }}"
      password: "{{ lookup('password', '{{ credential_store }}/SQL - {{ delegated_ca_login.username }}@{{ server.name }}_secret chars=ascii_letters,digits length=32') }}"
  when:  delegated_ca_login.password == ''


## certificate_login
- name: "Create a new password, or get the existing item for {{ certificate_login.username }}"
  block:
  - ansible.builtin.stat:
      path: "{{ keepass.database }}"
    register: kdbx

  - keepass:
      database: "{{ keepass.database }}"
      password: "{{ keepass.passwd | default(omit) }}"
      keyfile: "{{ keepass.keyfile | default(omit) }}"
      password_length: "{{ keepass.length }}"
      purpose: "{{certificate_login.username }}@Nextcloud"
      username: "{{ certificate_login.username }}"
    when: kdbx.stat.mimetype is defined and kdbx.stat.mimetype == 'application/octet-stream'
    register: certificate_login_tempo

  - ansible.builtin.set_fact:
      certificate_login:
        password: "{{ certificate_login_tempo.password | default('') }}"
      when: certificate_login_tempo.skipped is not defined

  delegate_to: localhost
  when: certificate_login.password == ''
  ignore_errors: true

- name: "Generate the password if is empty."
  ansible.builtin.set_fact:
    certificate_login:
      username: "{{ certificate_login.username }}"
      password: "{{ lookup('password', '{{ credential_store }}/{{ certificate_login.username }}@Nextcloud_secret chars=ascii_letters,digits length=32') }}"
  when:  certificate_login.password == ''
